---
title: "UBC STAT 550 Grapevine project - EDA plots"
output: pdf_document
editor_options: 
  chunk_output_type: inline
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
```

# Read data
```{r read.data.in}
chardonnay2019 = read.csv("TanjaVoegel_Chardonnay_2019_data.csv")
chardonnay2020 = read.csv("TanjaVoegel_Chardonnay_2020_data.csv")
merlot2019 = read.csv("TanjaVoegel_Merlot_2019_data.csv")
merlot2020 = read.csv("TanjaVoegel_Merlot_2020_data.csv")
addition2021 = read.csv("data addition March 8 2021.csv")

# removing extra columns
merlot2020 = merlot2020[-(61:65),]
merlot2020 = merlot2020[,-(19:20)]
merlot2019 = merlot2019[-(61:65),]
merlot2019 = merlot2019[,-18]

# Make sure the merlot column names are consistent
colnames(merlot2020)[colnames(merlot2020)=="spad"] = "SPAD"

# encode row, treatment, block, and subsample as factor
chardonnay2019$row = as.factor(chardonnay2019$row)
chardonnay2019$treatment = as.factor(chardonnay2019$treatment)
chardonnay2019$block = as.factor(chardonnay2019$block)
chardonnay2019$subsample = as.factor(chardonnay2019$subsample)

chardonnay2020$row = as.factor(chardonnay2020$row)
chardonnay2020$treatment = as.factor(chardonnay2020$treatment)
chardonnay2020$block = as.factor(chardonnay2020$block)
chardonnay2020$subsample = as.factor(chardonnay2020$subsample)

merlot2019$row = as.factor(merlot2019$row)
merlot2019$treatment = as.factor(merlot2019$treatment)
merlot2019$block = as.factor(merlot2019$block)
merlot2019$subsample = as.factor(merlot2019$subsample)


merlot2020$row = as.factor(merlot2020$row)
merlot2020$treatment = as.factor(merlot2020$treatment)
merlot2020$block = as.factor(merlot2020$block)
merlot2020$subsample = as.factor(merlot2020$subsample)

library(plyr)
# Add in the additional data
names(merlot2020)[1] <- "Key"
merlot2020 <- join(merlot2020, addition2021)
# detach plyr as it creates conflict with tidyverse
detach(package:plyr)

```

# Load Packages

```{r packages}
library(tidyverse)
library(ggpubr) 
library(corrplot)
library(icenReg) # for survival analysis
library(knitr)
library(lawstat) # for the levene test
library(mice)
library(miceadds)
library(MKinfer)
library(kableExtra)
library(rstatix) # for the repeated-measures ANOVA
library(ARTool) # for aligned rank transform
library(maditr) # for dcast
library(pwr2)
library(survival)
library(survminer)
```

# EDA: correlation plots
## chardonnay 2019

```{r}
char19.resp<-select(chardonnay2019, -1:-5)
char19.resp %>% 
  cor() %>% 
  corrplot(type = "upper", order = "hclust", tl.col = "black", tl.srt = 45, addCoef.col="white", number.cex=0.7)
```

## chardonnay 2020

```{r}
char20.resp<-select(chardonnay2020,-1:-5)
char20.resp %>% 
  cor() %>% 
  corrplot(type = "upper", order = "hclust", tl.col = "black", tl.srt = 45, addCoef.col="white", number.cex=0.7)
```

## merlot 2019

```{r}
merlot19.resp <- select(merlot2019,(-1:-5))
merlot19.resp %>%
  drop_na() %>% 
  cor() %>%
  corrplot(type = "upper", order = "hclust", tl.col = "black", tl.srt = 45, addCoef.col="white", number.cex=0.7)
```

## merlot 2020

```{r}
merlot20.resp <- select(merlot2020,(-1:-5))
merlot20.resp %>%
  drop_na() %>% 
  cor() %>%
  corrplot(type = "upper", order = "hclust", tl.col = "black", tl.srt = 45, addCoef.col="white", number.cex=0.7)
```

# EDA: summary statistics

```{r}
## helper function
summary.cont<-function(data, x){
  data %>% 
    summarise(min = round(min(x,na.rm=TRUE),2),
              median = round(median(x,na.rm=TRUE), 2),
              max= round(max(x,na.rm=TRUE), 2),
              mean = round(mean(x,na.rm=TRUE),2),
              sd = round(sd(x,na.rm=TRUE),2))
}

# Chardonnay 2019
sapply(char19.resp, summary.cont, data=char19.resp)
#var.desc1=sapply(char19.resp, summary.cont, data=char19.resp)
#kable(var.desc1, "latex", align ="c")


# Chardonnay 2020
sapply(char20.resp, summary.cont, data=chardonnay2020)
#var.desc2=sapply(char20.resp, summary.cont, data=chardonnay2020)
#kable(var.desc2, "latex", align ="c")

# Merlot 2019
sapply(merlot19.resp, summary.cont, data=merlot19.resp)
#var.desc3=sapply(merlot19.resp, summary.cont, data=merlot19.resp)
#kable(var.desc3, "latex", align ="c")

# Merlot 2020
sapply(merlot20.resp, summary.cont, data=merlot2020)
#var.desc4=sapply(merlot20.resp, summary.cont, data=merlot2020)
#kable(var.desc4,"latex", align ="c")
```

# EDA: Side by side box plots (ignoring blocks)

```{r}
# helper function
plot_resp = function(data, resp){
  ggplot(data, aes(x=treatment, y = .data[[resp]], fill=treatment))+
    scale_fill_manual(values=c("lightblue2", "seashell2"))+
    ylab(" ") +
    xlab(" ") +
    labs(title = resp) +
    theme(legend.position = "none")+
    geom_boxplot()+
    stat_compare_means(method = "t.test", label.x = 1.7,
                       label.y = min(data[[resp]])) +
    stat_compare_means(method = "wilcox.test", label.x = 0.7,
                       label.y = min(data[[resp]]))
}
```

## chardonnay 2019

```{r}
char2019.resp <- select(chardonnay2019,(-1:-5))
plot_list1= lapply(colnames(char2019.resp), plot_resp, data = chardonnay2019)
ggarrange(plotlist = plot_list1)
```

## chardonnay 2020

```{r}
char2020.resp <- select(chardonnay2020, (-1:-5))
plot_list2=lapply(colnames(char2020.resp),plot_resp, data=chardonnay2020)
ggarrange(plotlist = plot_list2)
```

## merlot 2019

```{r}
plot_list3=lapply(colnames(merlot2019[-c(1:5)]), plot_resp, data=drop_na(merlot2019))
ggarrange(plotlist = plot_list3)
```

## merlot 2020

```{r}
plot_list4=lapply(colnames(merlot2020[-c(1:5)]), plot_resp, data=drop_na(merlot2020))
ggarrange(plotlist = plot_list4, heights = 2)
```

# EDA: Side by side box plots (treatment - blocks combination)

```{r}
#helper function
plot.trt.blk=function(data, resp)
data %>% 
  ggplot(aes(x=treatment, y = .data[[resp]], fill=treatment))+
  scale_fill_manual(values=c("lightblue2", "seashell2"))+
  geom_boxplot()+
  labs(title = resp) +
  ylab(resp)+
  facet_wrap(~block)+
  theme_bw()+
  theme(legend.position = "top")+
  stat_compare_means(method = "wilcox.test", label.x = 0.7,
                     label.y = quantile(data[[resp]], probs=c(0.99), na.rm=TRUE))+
  stat_compare_means(method = "t.test", label.x = 1.7,
                     label.y = quantile(data[[resp]], probs=c(0.99), na.rm=TRUE))
```

## chardonnay 2019

```{r}
for (i in colnames(chardonnay2019[-1:-5])){
    print(plot.trt.blk(chardonnay2019, i))
}
```

## chardonnay 2020

```{r}
for (i in colnames(chardonnay2020[-1:-5])){
    print(plot.trt.blk(chardonnay2020, i))  
}
```

## merlot 2019

```{r}
for (i in colnames(merlot2019[c(-1:-5,-7)])){
  jpeg(file = mypath)
    print(plot.trt.blk(merlot2019, i))
  dev.off()
}
```

## merlot 2020

```{r}
for (i in colnames(merlot2020[-1:-5])){
    print(plot.trt.blk(merlot2020, i))
}
```

# KM curves for censored data (veraison and bloom)

```{r}
# veraison 2019
ver19<-merlot2019 %>% 
  select(treatment, veraison, block) %>% 
  mutate(veraison = replace_na(veraison, 0),
         status = ifelse(veraison <= 31, 1, 0)) #define the time-to-event as T<=31

fit1<-survfit(Surv(veraison, status) ~ treatment, data=ver19)
ggsurvplot(fit1, facet.by = "block", xlim = c(8, 40),pval=TRUE, 
           data=ver19,pval.coord=c(10,0.25),conf.int=TRUE,
           font.title=11,font.x=11,font.y=11,ylab="Non-veraison probability")

# veraison 2020
ver20<-merlot2020 %>% 
  select(treatment, veraison, block) %>% 
  mutate(veraison = replace_na(veraison, 0),
         status = ifelse(veraison <= 31, 1, 0)) #define the time-to-event as T<=31

fit2<-survfit(Surv(veraison, status) ~ treatment, data=ver20)
ggsurvplot(fit2, facet.by = "block", xlim = c(8, 40),pval=TRUE, 
           data=ver20,pval.coord=c(10,0.25),conf.int=TRUE,
           font.title=11,font.x=11,font.y=11,ylab="Non-veraison probability")


# bloom 2020
blm20<-merlot2020 %>% 
  select(treatment, bloom, block) %>% 
  mutate(bloom = replace_na(bloom, 0),
         status = ifelse(bloom <= 31, 1, 0)) #define the time-to-event as T<=31

fit3<-survfit(Surv(bloom, status) ~ treatment, data=blm20)
ggsurvplot(fit3, facet.by = "block", xlim = c(8, 40),pval=TRUE, 
           data=blm20,pval.coord=c(10,0.25),conf.int=TRUE,
           font.title=11,font.x=11,font.y=11,ylab="Non-bloom probability")
```