---
title: "Grapevine"
author: "Shannon Edie"
date: "26/01/2021"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Define the data

```{r create.data.frame}

library(plyr)


char19 <- read.csv("C:/Users/Shannon/Documents/STAT_550/Project_grapevine/data/Chardonnay_2019.csv")
char20 <- read.csv("C:/Users/Shannon/Documents/STAT_550/Project_grapevine/data/Chardonnay_2020.csv")

mer19 <- read.csv("C:/Users/Shannon/Documents/STAT_550/Project_grapevine/data/Merlot_2019.csv")
mer20 <- read.csv("C:/Users/Shannon/Documents/STAT_550/Project_grapevine/data/Merlot_2020.csv")

char19$year <- "2019"
char20$year <- "2020"
mer19$year <- "2019"
mer20$year <- "2020"

char <- rbind(char19, char20)
colnames(char) <- c("Key", "row", "treatment", "block", "subsample", "cluster.number",
                    "yield", "cluster.weight", "year")

mer19$X <- NULL
mer20$X <- NULL
mer20$X.1 <- NULL
colnames(mer20)[colnames(mer20)=="spad"] <- "SPAD"
mer <- rbind.fill(mer19, mer20)
colnames(mer)[grep("Key", colnames(mer))] <- "Key"


# remove blank rows
na.count.mer <- apply(mer, 1, FUN=function(x){sum(is.na(x))})
mer <- mer[na.count.mer!=18,]
na.count.mer <- apply(mer, 1, FUN=function(x){sum(is.na(x))})

```

# Univariate boxplots

```{r char.univ}

# Let's check distributions of variables
colnames(char)
resp.char <- c("cluster.number", "yield", "cluster.weight")
par(mfrow=c(2,2), mar=c(1,2,2,1))
for (i in 1:length(resp.char)) {
  boxplot(char[,which(names(char)==resp.char[i])], cex.main=1, main=resp.char[i])
}

```

```{r mer.univ}

colnames(mer)
resp.mer <- c("SPAD", "veraison", "cluster.number",
              "yield", "cluster.weight", "berries.cluster",
              "berry.weight", "berry.TA", "berry.pH",
              "berry.Brix", "pruning.weight", "Ravaz.index",
              "fruitfulness", "bloom", "brown.seed.color")

# Strictly univariate: check for outliers
par(mfrow=c(4,4), mar=c(1,2,2,1))
for (i in 1:length(resp.mer)) {
  boxplot(mer[,which(names(mer)==resp.mer[i])], cex.main=0.9, main=resp.mer[i])
}
```

# Assumptions

## Homoscedasticity

```{r homoscedas.merlot}

library(lawstat)

# Compare variance between treatment
par(mfrow=c(4,4), mar=c(1,2,2,1))
for (i in 1:length(resp.mer)) {
  var <- mer[,which(names(mer)==resp.mer[i])]
  boxplot(var[!is.na(var)] ~ mer$treatment[!is.na(var)], 
          cex.main=0.9, main=resp.mer[i])
  p <- bartlett.test(var[!is.na(var)] ~ mer$treatment[!is.na(var)])$p.value
  p.2 <- levene.test(var[!is.na(var)], 
                     as.factor(mer$treatment[!is.na(var)]))$p.value
  print(paste(resp.mer[i], round(p, 3), round(p.2, 3)))
}
# Compare variance between blocks
par(mfrow=c(4,4), mar=c(1,2,2,1))
for (i in 1:length(resp.mer)) {
  var <- mer[,which(names(mer)==resp.mer[i])]
  boxplot(var[!is.na(var)] ~ mer$block[!is.na(var)], 
          cex.main=0.9, main=resp.mer[i])
  p <- bartlett.test(var[!is.na(var)] ~ mer$block[!is.na(var)])$p.value
  p.2 <- levene.test(var[!is.na(var)], 
                     as.factor(mer$block[!is.na(var)]))$p.value
  print(paste(resp.mer[i], round(p, 3), round(p.2, 3)))
}

```

```{r homoscedas.char}

# Compare variance between treatment
par(mfrow=c(2,2), mar=c(1,2,2,1))
for (i in 1:length(resp.char)) {
  boxplot(char[,which(names(char)==resp.char[i])] ~ char$treatment, cex.main=0.9, main=resp.char[i])
  p <- bartlett.test(char[,which(names(char)==resp.char[i])] ~ char$treatment)$p.value
  print(paste(resp.char[i], p))
}
# Compare variance between blocks
par(mfrow=c(2,2), mar=c(1,2,2,1))
for (i in 1:length(resp.char)) {
  boxplot(char[,which(names(char)==resp.char[i])] ~ char$block, cex.main=0.9, main=resp.char[i])
  p <- bartlett.test(char[,which(names(char)==resp.char[i])] ~ char$block)$p.value
  print(paste(resp.char[i], p))
}
```

## Normality

```{r}

# Check normality
for (i in 1:length(resp.mer)) {
  qqnorm(mer[mer$treatment=="heat",which(names(mer)==resp.mer[i])], cex.main=0.9, main=resp.mer[i])
  qqline(mer[mer$treatment=="heat",which(names(mer)==resp.mer[i])], cex.main=0.9, main=resp.mer[i])
}
for (i in 1:length(resp.mer)) {
  qqnorm(mer[mer$treatment=="control",which(names(mer)==resp.mer[i])], cex.main=0.9, main=resp.mer[i])
  qqline(mer[mer$treatment=="control",which(names(mer)==resp.mer[i])], cex.main=0.9, main=resp.mer[i])
}

```

# Censoring

```{r}

mer$veraison.censor <- 1-as.numeric(is.na(mer$veraison))
mer$veraison.surv <- mer$veraison
mer$veraison.surv[is.na(mer$veraison.surv)] <- max(mer$veraison.surv, na.rm=T)

library(survival)
verais.cox <- coxph(Surv(mer$veraison.surv, mer$veraison.censor) ~ mer$treatment + as.character(mer$block) + mer$year)

verais.weib <- survreg(Surv(mer$veraison.surv, mer$veraison.censor) ~ mer$treatment + as.character(mer$block) + mer$year, dist="weibull")
verais.lnorm <- survreg(Surv(mer$veraison.surv, mer$veraison.censor) ~ mer$treatment + as.character(mer$block) + mer$year, dist="lognorm")
verais.llog <- survreg(Surv(mer$veraison.surv, mer$veraison.censor) ~ mer$treatment + as.character(mer$block) + mer$year, dist="loglogistic")

plot(survfit(verais.cox))

```

```{r}

mer$bloom.start <- 0
mer$bloom.end <- mer$bloom
mer$bloom.end[is.na(mer$bloom.end)] <- 1
mer$bloom.censor <- 1+as.numeric(is.na(mer$bloom))

# Uncensored means start = end
# Left-censored means we should leave start as NA
bloom.surv <- Surv(time=mer$bloom.end[mer$year==2020],
                   time2=rep(NA, sum(mer$year==2020)),
                   event=mer$bloom.censor[mer$year==2020],
                   type='interval')

library(survival)
bloom.cox <- coxph(bloom.surv ~ mer$treatment[mer$year==2020] + as.character(mer$block[mer$year==2020]))

bloom.weib <- survreg(bloom.surv ~ mer$treatment[mer$year==2020] + as.character(mer$block[mer$year==2020]), dist="weibull")
bloom.lnorm <- survreg(Surv(mer$bloom.surv, mer$bloom.censor) ~ mer$treatment + as.character(mer$block) + mer$year, dist="lognorm")
bloom.llog <- survreg(Surv(mer$bloom.surv, mer$bloom.censor) ~ mer$treatment + as.character(mer$block) + mer$year, dist="loglogistic")

plot(survfit(bloom.cox))


```




# Correlations in missing data

```{r}

# do a quick analysis to see if there are any issues with the missing variables
missing <- as.data.frame(lapply(mer, is.na))
missing <- missing[,unlist(lapply(mer, function(x){sum(is.na(x))>0}))] # only include the variables with missing data


# Write a function that runs a simple ANOVA
na.trt <- function(na.var, categ.var=NULL,
                           cont.var=NULL){
  if (!is.null(categ.var)){chisq.test(categ.var, na.var)$p.value
  } else if (!is.null(cont.var)){t.test(cont.var~na.var)
  }
}
lapply(missing, na.trt, categ.var=mer$block)

```
